apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: scanio-main-cronjob-manager
  # namespace: default
  {{- with .Values.commonLabels }}
  labels:
    {{- toYaml . | nindent 4 }}
  {{- end }}
rules:
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - list
  - get
  - create
  - update
  - patch 
  - delete
- apiGroups: [""]
  resources: ["secrets", "pods", "configmaps"]
  verbs: ["get", "list", "create", "update", "patch", "delete"]