kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: my-pv-claim
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi

---
apiVersion: v1
kind: Pod
metadata:
  name: test-pod
spec:
  serviceAccountName: {{ include "scanio-main.serviceAccountName" . }}
  containers:
  - name: test-pod
    image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
    imagePullPolicy: Never
    env:
      - name: JOB_HELM_CHART_PATH
        value: /scanio-helm/scanio-job
    command:
    {{- range .Values.command }}
      - {{ . }}
    {{- end }}
    # args: ["-c", "while true; do echo $(date -u) >> /data/out1.txt; sleep 5; done"]
    {{- if .Values.pv.efs.enabled }}
    volumeMounts:
    - name: my-pv-claim-vol
      mountPath: /data
    {{- end }}
    {{- if .Values.pv.efs.enabled }}
  volumes:
  - name: my-pv-claim-vol
    persistentVolumeClaim:
      # claimName: {{ .Values.pv.efs.claimName }}
      claimName: my-pv-claim
  {{- end }}
