apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: scanio-main-job-manager
  namespace: default
rules:
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - list
  - get
  - create
  - delete
- apiGroups: [""]
  resources: ["secrets", "pods","persistentvolumes"]
  verbs: ["get", "list", "create", "delete"]