kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: my-pv-claim
spec:
  accessModes:
    - ReadWriteMany
  # resources:
  #   requests:
  #     storage: 5Gi
capacity:
    storage: 5Gi
  hostPath:
    path: /data

---
apiVersion: batch/v1
kind: Job
metadata:
  name: scanio-job-{{ if .Values.suffix }}{{ .Values.suffix }}{{ else }}{{ randAlphaNum 5 | lower }}{{ end }}
  labels:
    {{- include "scanio-job.labels" . | nindent 4 }}
spec:
  backoffLimit: 1
  activeDeadlineSeconds: 1337
  template:
    metadata:
      name: scanio
      labels:
        {{- include "scanio-job.selectorLabels" . | nindent 8 }}
    spec:
      restartPolicy: Never
      containers:
      - name: {{ .Chart.Name }}
        command:
        {{- range .Values.command }}
          - {{ . }}
        {{- end }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        # imagePullPolicy: {{ .Values.image.pullPolicy }}
        imagePullPolicy: Never
        env:
        - name: SCANIO_HOME
          value: /data
        - name: SCANIO_PLUGINS_FOLDER
          value: /scanio-plugins
        {{- if .Values.pv.efs.enabled }}
        volumeMounts:
        - name: my-pv-claim-vol
          mountPath: /data
        {{- end }}
      {{- if .Values.pv.efs.enabled }}
      volumes:
      - name: my-pv-claim-vol
        persistentVolumeClaim:
          claimName: my-pv-claim
      {{- end }}