replicaCount: 1

image:
  repository: scanio
  pullPolicy: IfNotPresent
  # pullPolicy: Always
  tag: latest

command:
  - sleep
  - infinity

commonLabels:
  scanio-key: scanio-value

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: "scanio-main-pod"

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}

resources: {}
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

persistence:
  enabled: false
  claimName: pv-claim
  mountPath: /data
  # capacity: 20Gi

