apiVersion: v1
kind: PersistentVolume
metadata:
  name: volume-minikube
  labels:
    type: local
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  hostPath:
    path: /data/scanio
