replicaCount: 1

image:
  repository: scanio
  pullPolicy: Never # mandatory for a local minikube work
  tag: latest

command:
  - sleep
  - infinity

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: "scanio-main"

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}


resources: {}
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

pv:
  efs:
    enabled: true
    claimName: pv-claim
    mountPath: /data
