apiVersion: v1
kind: PersistentVolume
metadata:
  name: volume1
  labels:
    type: local
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  hostPath:
    path: "/data/scanio"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pv-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: test-pod
spec:
  serviceAccountName: {{ include "scanio-main.serviceAccountName" . }}
  containers:
  - name: test-pod
    image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
    imagePullPolicy: {{ .Values.image.pullPolicy }}
    env:
      - name: JOB_HELM_CHART_PATH
        value: /scanio-helm/scanio-job
    command:
    {{- range .Values.command }}
      - {{ . }}
    {{- end }}
    {{- if .Values.pv.efs.enabled }}
    volumeMounts:
    - name: pv-claim-vol
      mountPath: /data/
    {{- end }}
    {{- if .Values.pv.efs.enabled }}
  volumes:
  - name: pv-claim-vol
    persistentVolumeClaim:
      claimName: {{ .Values.pv.efs.claimName }}
  {{- end }}