apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: scanio-main-rolebinding
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: scanio-main-job-manager
subjects:
- kind: ServiceAccount
  name: {{ include "scanio-main.serviceAccountName" . }}
  namespace: default