apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: scanio-main-cronjob-rolebinding
  # namespace: default
  {{- with .Values.commonLabels }}
  labels:
    {{- toYaml . | nindent 4 }}
  {{- end }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: scanio-main-cronjob-manager
subjects:
- kind: ServiceAccount
  name: {{ include "scanio-main.serviceAccountName" . }}
  # namespace: default