on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to test scanio action
    # permissions:
    #   packages: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Scanio analyze
        id: scanio-action
        uses: scan-io-git/scanio-action/analyze@5231362f5022754d329b40aa04050858bc77e123
        with:
          scanner: semgrep

      - name: Upload SARIF results
        uses: github/codeql-action/upload-sarif@v2
