on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to test scanio action
    # permissions:
    #   packages: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Scanio analyze
        id: scanio-action
        # uses: scan-io-git/scanio-action/scanio@8da1e4e202241b83aa49610fc36619ed77b52230
        # run: scanio analyse --help
        uses: scan-io-git/scanio-action/analyze@624e6b6f6dd03957ec1536a0dfaf788714356f1b
        with:
          scanner: semgrep
      # Use the output from the `hello` step
      # - name: Get the output time
      #   run: echo "The time was ${{ steps.hello.outputs.time }}"
