name: "Scanio over Semgrep"

on:
  push:
    branches: [ "main" ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ "main" ]
  schedule:
    - cron: '37 10 * * 5'

jobs:
  scanio-action-job:
    runs-on: ubuntu-latest
    name: A job to run Scanio over Semgrep
    # permissions:
    #   packages: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Scanio analyze
        id: scanio-action
        uses: scan-io-git/scanio-action/analyze@v0.1.0
        with:
          scanner: semgrep

      - name: Upload SARIF results
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: '.'
      
      - name: Scanio to html
        uses: scan-io-git/scanio-action/to-html@d89db494b1096af9e598ae0f03577986c068c565
        with:
          input: scanio-report-semgrep.sarif
          output: scanio-report-semgrep.html

      - name: Upload scanio report
        uses: actions/upload-artifact@v4
        with:
          name: scanio-report
          path: scanio-report-semgrep.html
