name: "Scanio over Trufflehog"

on:
  push:
    branches: [ "main", "japroc/scanio-over-trufflehog" ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ "main", "japroc/scanio-over-trufflehog" ]
  schedule:
    - cron: '37 10 * * 5'

jobs:
  scanio-over-trufflehog-job:
    runs-on: ubuntu-latest
    name: A job to run Scanio over Trufflehog
    # permissions:
    #   packages: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Scanio analyze
        id: scanio-action
        uses: scan-io-git/scanio-action/analyze@051d8a9b47de47b15d2984a86ee5a6bb5545c4cd
        with:
          scanner: trufflehog
          format: json
