name: "Scanio for Semgrep"

on:
  push:
    branches: [ "main", "japroc/experiment-with-to-html-action"]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ "main", "japroc/experiment-with-to-html-action"]
  schedule:
    - cron: '37 10 * * 5'

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to test scanio action
    # permissions:
    #   packages: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Scanio analyze
        id: scanio-action
        uses: scan-io-git/scanio-action/analyze@5231362f5022754d329b40aa04050858bc77e123
        with:
          scanner: semgrep

      - name: Upload SARIF results
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: '.'

      - name: Scanio to html
        uses: scan-io-git/scanio-action/to-html@fdd45089627bfa42714e8888f3c23d5e0e47f1f7
        with:
          input: scanio-report-semgrep.sarif
          output: scanio-report-semgrep.html

      - name: Upload scanio report
        uses: actions/upload-artifact@v4
        with:
          name: scanio-report
          path: scanio-report-semgrep.html
