on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to test scanio action
    # permissions:
    #   packages: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Scanio analyze
        id: scanio-action
        # uses: scan-io-git/scanio-action/scanio@8da1e4e202241b83aa49610fc36619ed77b52230
        # run: scanio analyse --help
        uses: scan-io-git/scanio-action/analyze@56dbbd3e944f2e9b348ce2353e83254e25cb0aba
        with:
          scanner: semgrep

      - name: Upload SARIF results
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: ${{ github.workspace }}
