name: "Scanio over Trufflehog"

on:
  push:
    branches: [ "main", "japroc/scanio-over-trufflehog" ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ "main", "japroc/scanio-over-trufflehog" ]
  schedule:
    - cron: '37 10 * * 5'

jobs:
  scanio-over-trufflehog-job:
    runs-on: ubuntu-latest
    name: A job to run Scanio over Trufflehog
    # permissions:
    #   packages: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Scanio analyze
        id: scanio-action
        uses: scan-io-git/scanio-action/analyze@107c5a545de8f2841b7b860a496ca67d136e9a9a
        with:
          scanner: trufflehog
          format: json
          extra_args: "-x '.git'"

      - name: Upload scanio report
        uses: actions/upload-artifact@v4
        with:
          name: scanio-report
          path: scanio-report-trufflehog.json
