on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to test scanio action
    # permissions:
    #   packages: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Scanio analyze
        id: scanio-action
        # uses: scan-io-git/scanio-action/scanio@8da1e4e202241b83aa49610fc36619ed77b52230
        uses: scan-io-git/scanio-action/analyze@48c2da9041882fd7c61e19e41362d17701865688
        # run: scanio analyse --help
        with:
          scanner: semgrep
      # Use the output from the `hello` step
      # - name: Get the output time
      #   run: echo "The time was ${{ steps.hello.outputs.time }}"
